name: 'VHS Action'
description: 'Run VHS to render terminal videos'
inputs:
  version:
    description: VHS version
    default: latest
  path:
    description: 'The tape file path'
    default: 'vhs.tape'
  token:
    description: Used to pull VHS from Github
    default: ${{ github.token }}
  install-fonts:
    description: Install
    default: 'true'

runs:
  using: 'node16'
  main: 'dist/index.js'
